In [1]:
using Revise
using NamedTrajectories

In [2]:
# define number of timesteps and timestep
T = 10
dt = 0.1

0.1

In [3]:
# build named tuple of components and data matrices
components = (
    x = rand(3, T),
    u = rand(2, T),
    Δt = fill(dt, 1, T),
)

(x = [0.4496800725856104 0.9444202418694286 … 0.8139795203906602 0.1952200344910019; 0.018389518741425803 0.8135630875886481 … 0.6900016542854644 0.5184685937664664; 0.3539498249704417 0.7913480250913939 … 0.7890191394358691 0.9099803925707678], u = [0.9891271992223536 0.6677769590374695 … 0.9824149705727606 0.9097830247604325; 0.9625668031577324 0.70471090680827 … 0.3375655007534575 0.005051745539493835], Δt = [0.1 0.1 … 0.1 0.1])

In [4]:
# build trajectory
traj = NamedTrajectory(components; timestep=:Δt, controls=:u)

NamedTrajectory([0.4496800725856104 0.9444202418694286 … 0.8139795203906602 0.1952200344910019; 0.018389518741425803 0.8135630875886481 … 0.6900016542854644 0.5184685937664664; … ; 0.9625668031577324 0.70471090680827 … 0.3375655007534575 0.005051745539493835; 0.1 0.1 … 0.1 0.1], [0.4496800725856104, 0.018389518741425803, 0.3539498249704417, 0.9891271992223536, 0.9625668031577324, 0.1, 0.9444202418694286, 0.8135630875886481, 0.7913480250913939, 0.6677769590374695  …  0.7890191394358691, 0.9824149705727606, 0.3375655007534575, 0.1, 0.1952200344910019, 0.5184685937664664, 0.9099803925707678, 0.9097830247604325, 0.005051745539493835, 0.1], 10, :Δt, 6, (x = 3, u = 2, Δt = 1, states = 4, controls = 2), NamedTuple(), NamedTuple(), NamedTuple(), NamedTuple(), (x = 1:3, u = 4:5, Δt = 6:6, states = [1, 2, 3, 6], controls = [4, 5]), (:x, :u, :Δt), (:u,))

In [5]:
# access data by name
traj.x # returns 3x10 matrix of x data

3×10 Matrix{Float64}:
 0.44968    0.94442   0.561824  0.43765    …  0.307236   0.81398   0.19522
 0.0183895  0.813563  0.157581  0.0103097     0.386559   0.690002  0.518469
 0.35395    0.791348  0.324936  0.401266      0.0356899  0.789019  0.90998

In [6]:
traj.u # returns 2x10 matrix of u data

2×10 Matrix{Float64}:
 0.989127  0.667777  0.656754  0.121273  …  0.779423  0.982415  0.909783
 0.962567  0.704711  0.904798  0.205482     0.557831  0.337566  0.00505175

In [7]:
z1 = traj[1] # returns TimeSlice with x and u data

TimeSlice(1, [0.4496800725856104, 0.018389518741425803, 0.3539498249704417, 0.9891271992223536, 0.9625668031577324, 0.1], (x = 1:3, u = 4:5, Δt = 6:6, states = [1, 2, 3, 6], controls = [4, 5]), (:x, :u, :Δt), (:u,))

In [8]:
z1.x # returns 3x1 matrix of x data

3-element Vector{Float64}:
 0.4496800725856104
 0.018389518741425803
 0.3539498249704417

In [9]:
z1.u # returns 2x1 matrix of u data

2-element Vector{Float64}:
 0.9891271992223536
 0.9625668031577324

In [10]:
z1.x # returns 3x1 matrix of x data
z1.u # returns 2x1 matrix of u data

2-element Vector{Float64}:
 0.9891271992223536
 0.9625668031577324

In [11]:
traj.data # returns data as 5x10 matrix

6×10 reshape(view(::Vector{Float64}, :), 6, 10) with eltype Float64:
 0.44968    0.94442   0.561824  0.43765    …  0.307236   0.81398   0.19522
 0.0183895  0.813563  0.157581  0.0103097     0.386559   0.690002  0.518469
 0.35395    0.791348  0.324936  0.401266      0.0356899  0.789019  0.90998
 0.989127   0.667777  0.656754  0.121273      0.779423   0.982415  0.909783
 0.962567   0.704711  0.904798  0.205482      0.557831   0.337566  0.00505175
 0.1        0.1       0.1       0.1        …  0.1        0.1       0.1

In [12]:
traj.names # returns names as tuple (:x, :u)

(:x, :u, :Δt)

In [13]:
plot(traj)

In [ ]:
plot("./demo.png", traj)